server:
  port: 9999

spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
    open-in-view: false
  h2:
    port: 9090
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:todo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

